// Code generated by ent, DO NOT EDIT.

package ent

import (
	"semantiker/orm/ent/cores"
	"semantiker/orm/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	coresFields := schema.Cores{}.Fields()
	_ = coresFields
	// coresDescCount is the schema descriptor for Count field.
	coresDescCount := coresFields[2].Descriptor()
	// cores.DefaultCount holds the default value on creation for the Count field.
	cores.DefaultCount = coresDescCount.Default.(int)
	// coresDescCreated is the schema descriptor for Created field.
	coresDescCreated := coresFields[3].Descriptor()
	// cores.DefaultCreated holds the default value on creation for the Created field.
	cores.DefaultCreated = coresDescCreated.Default.(func() string)
	// coresDescUpdated is the schema descriptor for Updated field.
	coresDescUpdated := coresFields[4].Descriptor()
	// cores.DefaultUpdated holds the default value on creation for the Updated field.
	cores.DefaultUpdated = coresDescUpdated.Default.(func() string)
}
